create table if not exists public.export_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_date date not null,
  used_count smallint not null default 0 check (used_count between 0 and 2),
  updated_at timestamptz not null default now(),
  primary key (user_id, usage_date)
);

create table if not exists public.export_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_date date not null,
  export_kind text not null check (export_kind in ('image', 'data')),
  export_label text not null,
  created_at timestamptz not null default now()
);

alter table public.export_usage enable row level security;
alter table public.export_events enable row level security;

create schema if not exists private;
revoke all on schema private from public;

drop policy if exists "users_read_own_export_usage" on public.export_usage;
create policy "users_read_own_export_usage"
  on public.export_usage
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "users_read_own_export_events" on public.export_events;
create policy "users_read_own_export_events"
  on public.export_events
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create or replace function private.claim_export_quota(requested_kind text, requested_label text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  current_usage_date date := timezone('Asia/Shanghai', now())::date;
  current_used_count smallint;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if requested_kind not in ('image', 'data') then
    raise exception 'Unsupported export kind';
  end if;

  insert into public.export_usage as usage (user_id, usage_date, used_count, updated_at)
  values (current_user_id, current_usage_date, 1, now())
  on conflict (user_id, usage_date) do update
    set used_count = usage.used_count + 1,
        updated_at = now()
    where usage.used_count < 2
  returning used_count into current_used_count;

  if current_used_count is null then
    select used_count
      into current_used_count
      from public.export_usage
      where user_id = current_user_id and usage_date = current_usage_date;

    return jsonb_build_object(
      'allowed', false,
      'used', coalesce(current_used_count, 2),
      'remaining', 0
    );
  end if;

  insert into public.export_events (user_id, usage_date, export_kind, export_label)
  values (current_user_id, current_usage_date, requested_kind, left(requested_label, 240));

  return jsonb_build_object(
    'allowed', true,
    'used', current_used_count,
    'remaining', greatest(0, 2 - current_used_count)
  );
end;
$$;

create or replace function public.claim_export_quota(requested_kind text, requested_label text)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.claim_export_quota(requested_kind, requested_label);
$$;

revoke all on function private.claim_export_quota(text, text) from public;
grant usage on schema private to authenticated;
grant execute on function private.claim_export_quota(text, text) to authenticated;
revoke all on function public.claim_export_quota(text, text) from public;
grant execute on function public.claim_export_quota(text, text) to authenticated;

revoke all on public.export_usage from anon;
revoke all on public.export_events from anon;
grant select on public.export_usage to authenticated;
grant select on public.export_events to authenticated;
